# Generated by Django 3.0.7 on 2020-06-10 00:43

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('HojaIndicacion', '0002_organizacion_matrona'),
    ]

    operations = [
        migrations.CreateModel(
            name='examenes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_examen', models.CharField(max_length=50)),
                ('tipo_examen', models.CharField(max_length=20)),
                ('especificaciones', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='hoja_indicaciones',
            name='Hora_cirugias',
            field=models.TimeField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hoja_indicaciones',
            name='hora_medicamento',
            field=models.TimeField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paciente',
            name='diagnostico',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hoja_indicaciones',
            name='examen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='HojaIndicacion.examenes'),
        ),
    ]
