# Generated by Django 3.0.7 on 2020-06-10 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HojaIndicacion', '0005_auto_20200609_2102'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recien_nacido',
            options={'verbose_name_plural': 'Recien Nacidos'},
        ),
    ]
