# Generated by Django 3.0.7 on 2020-06-16 23:22

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('HojaIndicacion', '0006_auto_20200610_1032'),
    ]

    operations = [
        migrations.CreateModel(
            name='agenda_matrona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Horas', models.TimeField()),
            ],
        ),
        migrations.DeleteModel(
            name='organizacion_matrona',
        ),
        migrations.AddField(
            model_name='hoja_indicaciones',
            name='hora_examen',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='agenda_matrona',
            name='actividades',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='HojaIndicacion.hoja_indicaciones'),
        ),
    ]
