# Generated by Django 3.0.5 on 2020-08-03 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HojaIndicacion', '0008_auto_20200617_1017'),
    ]

    operations = [
        migrations.CreateModel(
            name='hola',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Horas', models.TimeField()),
            ],
        ),
        migrations.AddField(
            model_name='hoja_indicaciones',
            name='preparacion_operacion',
            field=models.BooleanField(default=False),
        ),
        migrations.RemoveField(
            model_name='hoja_indicaciones',
            name='examen',
        ),
        migrations.AddField(
            model_name='hoja_indicaciones',
            name='examen',
            field=models.ManyToManyField(blank=True, to='HojaIndicacion.examene'),
        ),
        migrations.AlterField(
            model_name='hoja_indicaciones',
            name='fecha',
            field=models.DateField(auto_now=True),
        ),
    ]
