# Generated by Django 3.0.7 on 2020-08-03 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HojaIndicacion', '0008_auto_20200617_1017'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='embarazada',
            field=models.BooleanField(default=False),
        ),
    ]
