# Generated by Django 3.0.7 on 2020-08-04 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HojaIndicacion', '0009_auto_20200803_1847'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hoja_indicaciones',
            name='Hora_cirugias',
        ),
        migrations.RemoveField(
            model_name='hoja_indicaciones',
            name='hora_medicamento',
        ),
    ]
