# Generated by Django 3.0.7 on 2020-08-03 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HojaIndicacion', '0009_paciente_embarazada'),
    ]

    operations = [
        migrations.AddField(
            model_name='hoja_indicaciones',
            name='Alta',
            field=models.BooleanField(default=False),
        ),
    ]
