# Generated by Django 3.0.7 on 2020-08-04 03:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HojaIndicacion', '0010_auto_20200803_2328'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hoja_indicaciones',
            name='hora_examen',
        ),
        migrations.AddField(
            model_name='hoja_indicaciones',
            name='alta',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='hoja_indicaciones',
            name='control',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='HojaIndicacion.controles'),
        ),
        migrations.RemoveField(
            model_name='hoja_indicaciones',
            name='examen',
        ),
        migrations.AddField(
            model_name='hoja_indicaciones',
            name='examen',
            field=models.BooleanField(default=False),
        ),
    ]
