# Generated by Django 3.0.7 on 2020-08-03 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HojaIndicacion', '0011_auto_20200802_2119'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hoja_indicaciones',
            name='cirugias',
        ),
    ]
