# Generated by Django 3.0.7 on 2020-08-03 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HojaIndicacion', '0012_remove_hoja_indicaciones_cirugias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hoja_indicaciones',
            name='fecha',
            field=models.DateField(auto_now=True),
        ),
    ]
