# Generated by Django 3.0.7 on 2020-08-03 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HojaIndicacion', '0013_auto_20200802_2121'),
    ]

    operations = [
        migrations.AddField(
            model_name='hoja_indicaciones',
            name='hora_alta',
            field=models.DateField(default=None),
        ),
    ]
