# Generated by Django 3.0.7 on 2020-08-03 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HojaIndicacion', '0014_hoja_indicaciones_hora_alta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hoja_indicaciones',
            name='hora_alta',
        ),
    ]
